# Generated by Django 3.2.3 on 2021-06-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePhoto', models.FileField(default='uploads/default.png', upload_to='uploads/users/')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Content', models.TextField(max_length=50)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.user')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
